/**
 * Standalone verification of the cell loop — no LLM, no prime-agent.
 * Drives CellRunner directly through the six core scenarios (DESIGN.md §6.1).
 *
 * Run: node <prime-agent>/node_modules/tsx/dist/cli.mjs poc/test/loop-test.ts
 */

import assert from "node:assert";
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { CellRunner, composeToolText } from "../extension/runtime/cell-runner.ts";
import { resolveToolchain, warmTemplate } from "../extension/runtime/toolchain.ts";
import { createWorkspace, listPersistentState, removeWorkspace } from "../extension/runtime/workspace.ts";

const toolchain = resolveToolchain();
console.log(`toolchain: cargo=${toolchain.cargoBin} wasmedge=${toolchain.wasmedgeVersion.split("\n")[0]}`);
warmTemplate(toolchain.cargoBin);

// Fake project dir mounted at /workspace (HOME-based; readonly-safe paths).
const projectRoot = join(homedir(), ".wasmedge-agent", "poc", "test-project");
mkdirSync(projectRoot, { recursive: true });
const projectDir = mkdtempSync(join(projectRoot, "run-"));
writeFileSync(
	join(projectDir, "app.log"),
	["INFO boot", "ERROR db timeout", "WARN slow", "ERROR db timeout", "ERROR io fail", ""].join("\n"),
);

const workspaceDir = createWorkspace(`loop-test-${Date.now().toString(36)}`);
const runner = new CellRunner({
	cwd: projectDir,
	workspaceDir,
	wasmedgeBin: toolchain.wasmedgeBin,
	cargoBin: toolchain.cargoBin,
	cellTimeoutMs: 120_000,
});

let failures = 0;
function check(name: string, ok: boolean, detail?: string) {
	console.log(`${ok ? "PASS" : "FAIL"}  ${name}${detail ? `  (${detail})` : ""}`);
	if (!ok) failures += 1;
}

// 1. Plain cell: read the project, write state.
{
	const r = await runner.execute({
		code: `use agent_lib::prelude::*;
fn main() -> Result<()> {
    let lines = read_lines("/workspace/app.log")?;
    let errors = lines.iter().filter(|l| l.starts_with("ERROR")).count();
    rlm::state::set("error_count", &errors)?;
    println!("errors={errors}");
    Ok(())
}
`,
	});
	check("cell ok + stdout", r.status === "ok" && r.stdout.includes("errors=3"), `compile=${r.compileMs}ms run=${r.runMs}ms`);
}

// 2. State persists across cells.
{
	const r = await runner.execute({
		code: `use agent_lib::prelude::*;
fn main() -> Result<()> {
    let n: Option<usize> = rlm::state::get("error_count")?;
    println!("recalled={}", n.ok_or_else(|| anyhow!("state lost"))?);
    Ok(())
}
`,
	});
	check("state round-trip across cells", r.status === "ok" && r.stdout.includes("recalled=3"));
}

// 3. Compile error: diagnostics come back, cell does not run.
{
	const r = await runner.execute({
		code: `use agent_lib::prelude::*;
fn main() -> Result<()> {
    let x: u32 = "not a number";
    Ok(())
}
`,
	});
	const text = composeToolText(r);
	check(
		"compile error surfaces rustc diagnostics",
		r.status === "compile_error" && text.includes("mismatched types"),
		`compile=${r.compileMs}ms`,
	);
}

// 4. Lib param: add a helper module and use it in the same call.
{
	const r = await runner.execute({
		lib: [
			{
				path: "src/helpers/logstats.rs",
				content: `use crate::prelude::*;
pub fn count_matching(path: &str, pattern: &str) -> Result<usize> {
    let re = Regex::new(pattern)?;
    Ok(read_lines(path)?.iter().filter(|l| re.is_match(l)).count())
}
`,
			},
		],
		code: `use agent_lib::prelude::*;
fn main() -> Result<()> {
    let n = helpers::logstats::count_matching("/workspace/app.log", "^ERROR")?;
    println!("via-lib={n}");
    Ok(())
}
`,
	});
	check("lib file applied + used in same call", r.status === "ok" && r.stdout.includes("via-lib=3") && r.libApplied);
}

// 5. Lib survives to the next cell; helpers/mod.rs was regenerated by host.
{
	const r = await runner.execute({
		code: `use agent_lib::prelude::*;
fn main() -> Result<()> {
    println!("persisted={}", helpers::logstats::count_matching("/workspace/app.log", "ERROR")?);
    Ok(())
}
`,
	});
	const modRs = readFileSync(join(workspaceDir, "agent_lib", "src", "helpers", "mod.rs"), "utf-8");
	check("lib persists across cells", r.status === "ok" && r.stdout.includes("persisted=3"));
	check("helpers/mod.rs regenerated", modRs.includes("pub mod logstats;"));
}

// 6. Broken lib edit: reverted, cell not run, library still healthy.
{
	const r = await runner.execute({
		lib: [{ path: "src/helpers/broken.rs", content: "pub fn nope( -> {}" }],
		code: `use agent_lib::prelude::*;
fn main() -> Result<()> { Ok(()) }
`,
	});
	const text = composeToolText(r);
	check(
		"broken lib edit -> compile_error + revert notice",
		r.status === "compile_error" && r.libReverted && text.includes("reverted"),
	);
	const after = await runner.execute({
		code: `use agent_lib::prelude::*;
fn main() -> Result<()> {
    println!("healthy={}", helpers::logstats::count_matching("/workspace/app.log", "^ERROR")?);
    Ok(())
}
`,
	});
	check("library healthy after revert", after.status === "ok" && after.stdout.includes("healthy=3"));
}

// 7. Runtime error: nonzero exit surfaces as error with stderr.
{
	const r = await runner.execute({
		code: `use agent_lib::prelude::*;
fn main() -> Result<()> {
    bail!("intentional failure");
}
`,
	});
	const text = composeToolText(r);
	check(
		"runtime error -> status error + exit note",
		r.status === "error" && text.includes("intentional failure") && text.includes("exited with code"),
	);
}

// 8. Timeout: infinite loop is killed within budget.
{
	const fast = new CellRunner({
		cwd: projectDir,
		workspaceDir,
		wasmedgeBin: toolchain.wasmedgeBin,
		cargoBin: toolchain.cargoBin,
		cellTimeoutMs: 8_000,
	});
	const started = Date.now();
	const r = await fast.execute({
		code: `use agent_lib::prelude::*;
fn main() -> Result<()> {
    loop { std::hint::spin_loop(); }
}
`,
	});
	check("timeout kills runaway cell", r.status === "timeout" && Date.now() - started < 30_000, `${r.durationMs}ms`);
}

// 9. Persistent-state listing for compaction/resume notices.
{
	const listing = listPersistentState(workspaceDir);
	check(
		"listPersistentState sees keys + lib fns",
		listing.stateKeys.includes("error_count") && listing.libFunctions.includes("helpers::logstats::count_matching"),
		JSON.stringify(listing),
	);
}

console.log(failures === 0 ? "\nALL PASS" : `\n${failures} FAILURES`);
assert.equal(failures, 0);
removeWorkspace(workspaceDir);
